name: stat_flutter
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  html: ^0.15.0
  firebase_auth: ^2.0.0
  firebase_core: ^1.2.0
  cloud_firestore: ^2.2.0
  flutter_signin_button: ^2.0.0
  window_size:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
  flutter_webrtc: ^0.6.3
  web_socket_channel: ^2.1.0
  js: ^0.6.3
  google_ml_kit: ^0.6.0
  image_picker: ^0.8.0
  flutter_cache_manager: ^3.1.0
  firebase_ml_vision: ^0.12.0+2
  webview_flutter: ^2.0.8
  url_launcher: ^6.0.6

dev_dependencies:
  flutter_lints: ^1.0.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/logo.jpg
